{{- if index .Values "kubeclarity-trivy-server" "enabled" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeclarity.trivy-server.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.trivy-server.labels" . }}
{{- end}}
