{{- $secretName := index .Values "kubeclarity-postgresql-secret" "createPasswordSecretName" -}}
{{- $secretKey := index .Values "kubeclarity-postgresql-secret" "createPasswordSecretKey" -}}
{{- $postgresPassword := .Values.global.databasePassword | b64enc -}}
{{- if (index .Values "kubeclarity-postgresql-secret" "createPasswordSecret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.labels" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  {{ $secretKey }}: {{ $postgresPassword }}
{{- end }}
