{{- $secretName := index .Values "kubeclarity-postgresql" "auth" "existingSecret" -}}
{{- $postgresPassword := .Values.global.databasePassword | b64enc -}}
{{ if index .Values "kubeclarity-postgresql-external" "enabled" }}
  {{- $secretName = index .Values "kubeclarity-postgresql-external" "auth" "existingSecret" -}}
  {{- $postgresPassword := index .Values "kubeclarity-postgresql-external" "auth" "password" -}}
{{ end }}
{{- if or (index .Values "kubeclarity-postgresql" "enabled") (and (index .Values "kubeclarity-postgresql-external" "enabled") (index .Values "kubeclarity-postgresql-external" "auth" "password")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.labels" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  postgres-password: {{ $postgresPassword }}
{{- end }}
