{{- $secretName := index .Values "kubeclarity-postgresql" "auth" "existingSecret" -}}
{{ if index .Values "kubeclarity-postgresql-external" "enabled" }}
  {{- $secretName = index .Values "kubeclarity-postgresql-external" "auth" "existingSecret" -}}
{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.labels" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  postgres-password: {{ .Values.global.databasePassword | b64enc }}
