apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeclarity.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.labels" . }}
  annotations:
    helm.sh/hook: pre-install
{{ template "kubeclarity.service.annotations" .}}
spec:
  type: {{ .Values.kubeclarity.service.type }}
  ports:
    - name: backend
      port: {{ index .Values "kubeclarity" "service" "port" }}
      protocol: TCP
      targetPort: {{ index .Values "kubeclarity" "service" "targetPort" }}
    - name: runtime-scan-results
      port: {{ index .Values "kubeclarity-runtime-scan" "resultServicePort" }}
      protocol: TCP
      targetPort: {{ index .Values "kubeclarity-runtime-scan" "resultServicePort" }}
  selector:
    app: {{ include "kubeclarity.name" . }}
